environments:
  - env_name: dabstepgym
    env_image: ailab-evobox-evobox_cpu/evoboxenv:latest
    env_num: 1
    env_params:
      root: "D:/work/env_test/AIEvoBox"
      data_dir: "env/bench_env/dabstep/agent_core"
      context_dir: "pack/context"
      tasks_dir: "pack/tasks"
      artifacts_dir: "env/bench_env/dabstep/artifacts"
      runner_script: "env/bench_env/dabstep/agent_core/dabstep_runner.py"

      split: "dev"
      max_steps: 20
      timeout: 60
      limit: 0

      # ★ 任务分片：总3片，这是第0片
      num_shards: 3
      shard_index: 0
      tasks_shuffle: 1
      seed: 42

  - env_name: dabstepgym
    env_image: ailab-evobox-evobox_cpu/evoboxenv:latest
    env_num: 1
    env_params:
      root: "D:/work/env_test/AIEvoBox"
      data_dir: "env/bench_env/dabstep/agent_core"
      context_dir: "pack/context"
      tasks_dir: "pack/tasks"
      artifacts_dir: "env/bench_env/dabstep/artifacts"
      runner_script: "env/bench_env/dabstep/agent_core/dabstep_runner.py"

      split: "dev"
      max_steps: 20
      timeout: 60
      limit: 0

      # ★ 第1片
      num_shards: 3
      shard_index: 1
      tasks_shuffle: 1
      seed: 42

  - env_name: dabstepgym
    env_image: ailab-evobox-evobox_cpu/evoboxenv:latest
    env_num: 1
    env_params:
      root: "D:/work/env_test/AIEvoBox"
      data_dir: "env/bench_env/dabstep/agent_core"
      context_dir: "pack/context"
      tasks_dir: "pack/tasks"
      artifacts_dir: "env/bench_env/dabstep/artifacts"
      runner_script: "env/bench_env/dabstep/agent_core/dabstep_runner.py"

      split: "dev"
      max_steps: 20
      timeout: 60
      limit: 0

      # ★ 第2片
      num_shards: 3
      shard_index: 2
      tasks_shuffle: 1
      seed: 42
