environments:
  - env_name: os_gym
    env_image: registry.h.pjlab.org.cn/ailab-evobox-evobox_cpu/os-gym:v0.2.0
    env_num: 1
    dataset: /mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/Safactory/datasets/standard/osworld_no_chrome.jsonl  # JSONL dataset file with task configurations
    env_params:
      eval_mode: standard  # "standard" or "safety"
      provider_name: "docker"
      vm_path: "/mnt/shared-storage-gpfs2/evobox-share-gpfs2/kangzeyu/projects/AIEvoBox/env/osgym/docker_vm_data/Ubuntu.qcow2"
      prompt_observation_type: screenshot
      headless: true
      action_space: "pyautogui"
      prompt_format: qwen
      screen_width: 1920
      screen_height: 1080
      cache_dir: null  # Let each Ray actor create a unique /tmp/osgym_cache_<id> directory.
      sleep_after_execution: 1.0
      max_steps: 30
      # LLM Judge configuration
      llm_judge_config:
        api_key: your-api-key
        base_url: your-base-url
        model: your-model
