# 1. 指定基础镜像
FROM registry.h.pjlab.org.cn/ailab-evobox-evobox_cpu/ray:emb005

ENV http_proxy=http://leishanzhe:wSl49KRSqn71Jkqikb8tfZ8Lqxx5uGCgIEmiBGuDzH5r6uSpEN3nGLmsO7UE@proxy.h.pjlab.org.cn:23128
ENV https_proxy=http://leishanzhe:wSl49KRSqn71Jkqikb8tfZ8Lqxx5uGCgIEmiBGuDzH5r6uSpEN3nGLmsO7UE@proxy.h.pjlab.org.cn:23128


USER root

RUN apt update && apt install -y \
    --no-install-recommends \
    vim \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*


RUN if [ -d "/root/envs/embench1" ]; then \
    echo "Conda environment found at /root/envs/embench1"; \
    /root/envs/embench1/bin/pip install matplotlib ray==2.49.2 pillow; \
    else \
    echo "Warning: /root/envs/embench1 not found, using system pip"; \
    pip install matplotlib ray==2.49.2 pillow; \
    fi   


COPY env.yaml env.yaml

RUN conda env update -n base -f env.yaml && \
    conda clean -afy


EXPOSE 36663



