enabled_envs:
  - truthfulness

_templates:
  common_params: &common_params
    down_sample_ratio: 1.0
    start_epi_index: 0
    resolution: 500
    recording: false
    max_episode_steps: 20

  artifact_params: &artifact_params
    auto_save_artifacts: true
    save_step_images: true

  perturbation_params: &perturbation_params
    perturbation_type: none

  no_dynamic_perturbation: &no_dynamic_perturbation
    dynamic_perturbation: false

  truthfulness_params: &truthfulness_params
    <<: *common_params
    dataset_name: dataset.yaml

  robust_params: &robust_params
    <<: [*common_params, *artifact_params, *perturbation_params]
    dataset_name: dataset_robust.yaml

  robustd_params: &robustd_params
    <<: [*common_params, *artifact_params, *perturbation_params, *no_dynamic_perturbation]
    dataset_name: dataset.yaml

  safety_params: &safety_params
    <<: [*common_params, *artifact_params, *perturbation_params, *no_dynamic_perturbation]
    dataset_name: dataset_safety.yaml

environments:
  - env_name: rt_truthfulness
    env_num: 1
    env_params:
      <<: *truthfulness_params
      eval_set: truthfulness
      exp_name: aievobox_rt_truthfulness_truthfulness

  - env_name: rt_truthfulness
    env_num: 1
    env_params:
      <<: *truthfulness_params
      eval_set: truthfulness1
      exp_name: aievobox_rt_truthfulness_truthfulness1

  - env_name: rt_robust_base
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: base
      exp_name: aievobox_rt_robust_base

  - env_name: rt_robust_common_sense
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: common_sense
      exp_name: aievobox_rt_robust_common_sense

  - env_name: rt_robust_complex_instruction
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: complex_instruction
      exp_name: aievobox_rt_robust_complex_instruction

  - env_name: rt_robust_spatial_relationship
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: spatial_relationship
      exp_name: aievobox_rt_robust_spatial_relationship

  - env_name: rt_robust_visual_appearance
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: visual_appearance
      exp_name: aievobox_rt_robust_visual_appearance

  - env_name: rt_robust_long_horizon
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: long_horizon
      exp_name: aievobox_rt_robust_long_horizon

  - env_name: rt_robust_robust_robust_error
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: robust_robust_error
      exp_name: aievobox_rt_robust_robust_robust_error

  - env_name: rt_robust_robust_robust_redu
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: robust_robust_redu
      exp_name: aievobox_rt_robust_robust_robust_redu

  - env_name: rt_robust_robust_robust_sema
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: robust_robust_sema
      exp_name: aievobox_rt_robust_robust_robust_sema

  - env_name: rt_robust_robust_robust_raw
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: robust_robust_raw
      exp_name: aievobox_rt_robust_robust_robust_raw

  - env_name: rt_robust_robust_picture
    env_num: 1
    env_params:
      <<: *robust_params
      eval_set: robust_picture
      exp_name: aievobox_rt_robust_robust_picture

  - env_name: rt_robustd_base
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: base
      exp_name: aievobox_rt_robustd_base

  - env_name: rt_robustd_common_sense
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: common_sense
      exp_name: aievobox_rt_robustd_common_sense

  - env_name: rt_robustd_complex_instruction
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: complex_instruction
      exp_name: aievobox_rt_robustd_complex_instruction

  - env_name: rt_robustd_spatial_relationship
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: spatial_relationship
      exp_name: aievobox_rt_robustd_spatial_relationship

  - env_name: rt_robustd_visual_appearance
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: visual_appearance
      exp_name: aievobox_rt_robustd_visual_appearance

  - env_name: rt_robustd_long_horizon
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: long_horizon
      exp_name: aievobox_rt_robustd_long_horizon

  - env_name: rt_robustd_robust_robust_error
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: robust_robust_error
      exp_name: aievobox_rt_robustd_robust_robust_error

  - env_name: rt_robustd_robust_robust_redu
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: robust_robust_redu
      exp_name: aievobox_rt_robustd_robust_robust_redu

  - env_name: rt_robustd_robust_robust_sema
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: robust_robust_sema
      exp_name: aievobox_rt_robustd_robust_robust_sema

  - env_name: rt_robustd_robust_robust_raw
    env_num: 1
    env_params:
      <<: *robustd_params
      eval_set: robust_robust_raw
      exp_name: aievobox_rt_robustd_robust_robust_raw

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_1
      exp_name: aievobox_rt_safety_safety_1_1

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_2
      exp_name: aievobox_rt_safety_safety_1_2

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_3
      exp_name: aievobox_rt_safety_safety_1_3

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_4
      exp_name: aievobox_rt_safety_safety_1_4

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_5
      exp_name: aievobox_rt_safety_safety_1_5

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_6
      exp_name: aievobox_rt_safety_safety_1_6

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_7
      exp_name: aievobox_rt_safety_safety_1_7

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_8
      exp_name: aievobox_rt_safety_safety_1_8

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_9
      exp_name: aievobox_rt_safety_safety_1_9

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_1_10
      exp_name: aievobox_rt_safety_safety_1_10

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_1
      exp_name: aievobox_rt_safety_safety_2_1

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_2
      exp_name: aievobox_rt_safety_safety_2_2

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_3
      exp_name: aievobox_rt_safety_safety_2_3

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_4
      exp_name: aievobox_rt_safety_safety_2_4

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_5
      exp_name: aievobox_rt_safety_safety_2_5

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_6
      exp_name: aievobox_rt_safety_safety_2_6

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_7
      exp_name: aievobox_rt_safety_safety_2_7

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_8
      exp_name: aievobox_rt_safety_safety_2_8

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_9
      exp_name: aievobox_rt_safety_safety_2_9

  - env_name: rt_safety
    env_num: 1
    env_params:
      <<: *safety_params
      eval_set: safety_2_10
      exp_name: aievobox_rt_safety_safety_2_10
