[project]
name = "tradinggymserver"
version = "0.0.1"
description = ""
authors = [
    {name = "chenxinquan", email = "chenxinquan@pjlab.org.cn"},
]
dependencies = [
    "fastapi",
    "uvicorn",
    "gymnasium",
]
requires-python = ">=3.8"
readme = "README.md"
license = "MIT"

[project.scripts]
tradinglaunch = "tradinggym_server:launch"
