environments:
  - env_name: openrt
    env_image: b65104033c5d
    env_num: 1
    dataset: ./datasets/openrt_attacks.jsonl
    dataset_load_mode: eager

    env_params:
      task_family: openrt
      api_key: EMPTY
      default_openrt_dataset: harmbench
      default_attacker_model: kimi-k26-w4a8
      default_judge_model: glm51
      default_target_models:
        - dsv4pro
      max_workers: 50
      evaluator_workers: 32
